<a href="https://colab.research.google.com/github/Hongbi-Kim/DeepLearning/blob/master/colab_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 텍스트의 토큰화

## 주어진 문장을 '단어'로 토큰화 하기
- p246~247

In [ ]:
# 텍스트 전처리 함수 text_to_word_sequence() 호출
# 주어진 문장을 '단어'로 토큰화 하기(tokenize)

from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [ ]:
# 전처리할 텍스트 정하기
text = '해보지 않으면 해낼 수 없다'  # 문장 >> 단어

# 해당 텍스트 토큰화
result = text_to_word_sequence(text)
print('\n원문:\n', text)
print('\n토큰화:\n' , result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [ ]:
# 텍스트 전처리 함수 Tokenizer() 호출
# 단어의 빈도 수 계산
from keras.preprocessing.text import Tokenizer

In [ ]:
# 전처리 하려는 세개의 문장을 정하기

docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

In [ ]:
# 토큰화 함수를 이용해 전처리하는 과정
token = Tokenizer()       # 토큰화 함수 지정
token.fit_on_texts(docs)  # 토큰화 함수에 문장 적용

# 각 옵션에 맞춰 단어의 빈도 수를 계산한 결과 출력
# Tokenizer()의 word_counts 함수는 순서를 기억하는 OrderedDict 클래스 사용
print('\n단어 카운트:\n', token.word_counts) 

# 출력되는 순서는 랜덤
print('\n문장 카운트:\n', token.document_count)
print('\n각 단어가 몇 개의 문장에 포함되어 있는가:\n', token.word_docs)
print('\n각 단어에 매겨진 인덱스 값:\n', token.word_index)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트:
 3

각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'각': 1, '단어를': 1, '나누어': 1, '토큰화합니다': 1, '먼저': 1, '텍스트의': 2, '토큰화해야': 1, '단어로': 1, '딥러닝에서': 2, '인식됩니다': 1, '있습니다': 1, '사용할': 1, '결과는': 1, '수': 1, '토큰화한': 1})

각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


# 4. 텍스트를 읽고 긍정, 부정 예측하기
## 영화 리뷰가 긍정적인지 부정적인지 예측하기
- p257, 258

In [ ]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [ ]:
# 텍스트 리뷰 자료 지정
docs = ['너무 재밌네요','최고예요','참 잘 만든 영화예요','추천하고 싶은 영화입니다',
        '한번 더 보고싶네요','글쎄요','별로예요','생각보다 지루하네요',
        '연기가 어색해요','재미없어요']

In [ ]:
# 감성사전 : 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [ ]:
# 토큰에 지정된 인덱스로 새로운 배열을 생성
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [ ]:
# 패딩, 서로 다른 길이의 데이터를 지정된 값(여기서 4로 지정) 맞춤.
padded_x = pad_sequences(x,4)
print('\n패딩 결과\n', padded_x)


패딩 결과
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [ ]:
# 임베딩 함수에 필요한 세 가지 파라미터 : 입력, 출력, 단어 수
# 입력 : 총 몇 개의 단어 집합에서
# 출력 : 몇 개의 임베딩 결과를 사용할 것인지
# 단어 수 : 매번 입력될 단어 수는 몇 개로 할지

# 딥러닝 모델 적용
# 임베딩에 입력될 단어 수 지정
# 전체 단어의 맨 앞에 0이 먼저 나와야 하므로 총 단어 수에 1을 더해줌
word_size = len(token.word_index) + 1

In [ ]:
# 단어 임베딩(word embedding)을 포함하여 딥러닝 모델을 만들고 결과 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length = 4))
# word_size 만큼의 입력값, 8개의 임베딩 결과, input_length : 단어 수 지정
model.add(Flatten()) # 차원축소(2차원 >> 1차원)
model.add(Dense(1, activation = 'sigmoid')) # 출력층, 이진 분류(sigmoid)

model.compile(optimizer = 'adam', loss = 'binary_crossentropy',
              metrics = ['accuracy'])
model.fit(padded_x, classes, epochs = 20)

print('\n Accuracy: %.4f'%(model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 1s 541ms/step - loss: 0.6915 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6898 - accuracy: 0.7000
Epoch 3/20
1/1 [==============================] - 0s 15ms/step - loss: 0.6882 - accuracy: 0.8000
Epoch 4/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6865 - accuracy: 0.8000
Epoch 5/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6849 - accuracy: 0.9000
Epoch 6/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6832 - accuracy: 0.9000
Epoch 7/20
1/1 [==============================] - 0s 23ms/step - loss: 0.6816 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6799 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6783 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6766 - accuracy: 1.0000
Epoch 11/20
1/1 [===========

In [ ]:
# 학습 결과가 10개의 리뷰 샘플 중 몇 개를 맞추었는지 보여줌.